Pause Insert Disk # 1 of disk utilities
copy c:diskmenu.asm a:
copy c:disklook.asm a:
copy c:disktest.asm a:
copy c:diskint.asm a:
copy c:diskpmpt.asm a:
Pause Insert Disk # 2 of disk utilities
copy c:diskdisp.asm a:
copy c:diskerr.asm a:
copy c:diskkey.asm a:
copy c:diskdata.inc a:
copy b:diskbak.bat a:
copy b:disklk.bat a:
copy b:disklknl.bat a:
copy b:disklnk.lnk a:
copy b:disk.com a:

ike.s :
oycdsdt.n :
oybdsbkbtacp :ikkbtacp :ikklbtacp :ikn.n :
oybds.o :

ies:ocstn:obsktp:kbac ik